### ISSUE TITLE
QuickLisp Support

### ISSUE THREAD

**Issue by tanaytrivedi** [wzrdsappr/trading-core#1]
Hello,
So I tried recently downloading your code using QuickLisp, but it seems like it is no longer supported? I ran this line `(ql:quickload "trading-core")`, but as the attached output shows QuickLoad cannot find the file.
Thanks
![screen shot 2017-07-19 at 3 46 19 pm](https://user-images.githubusercontent.com/19849991/28386585-0e0e671e-6c9a-11e7-8929-7666dc2b4a0a.png)

**Comment by wzrdsappr** [comment]
Hello tanaytrivedi,
It seems my instructions on the home page are incomplete.  I have never submitted trading-core to be one of the systems included in quicklisp.  To use quicklisp to load the system, download the system into a folder in the quicklisp/local-projects folder or create a symbolic link to its location in that folder.  It should then be able to find the library.

**Comment by wzrdsappr** [comment]
Hello tanaytrivedi,

I have pushed up several bug fixes, along with better instructions on how to load and use the library.  Please let me know if these new instructions do not allow you to use the library.
